### ISSUE TITLE
Make folders nestable

### ISSUE THREAD

**Issue by mflux** [dataarts/dat.guiVR#28]

**Comment by xinaesthete** [comment]
I've made a fork in which I've hacked together a rough implementation of this feature.  Known bug as of this writing with sometimes being able to detach collapsed nested folders.

While I'm here, some further digressions...

I might slightly change the API to make it more similar to the original `dat.gui`, ie

    gui = dat.gui.create();
    folder = gui.addFolder("Empty folder")

etc.  It'd be nice to be compatible in the sense of being able to write

    function makeGUI(optionalVRScene) {
      var guiFactory = optionalVRScene ? dat.GUIVR : dat.gui;
      var gui = guiFactory.create();
      var f1 = gui.addFolder("folder");
      f1.add(settings, 'speed');
      // ... more gui creation that'll work as long as common features exist in both libs ... //
      if (optionalVRScene) optionalVRScene.add(gui);
    }

Although having said that, there's obviously quite a bit that's unlikely to be ported from `dat.gui` and from my point of view, if I carry on working with `dat.GUIVR` then I'll probably start adding a few things with no `dat.gui` counterpart anyway.

It'd make sense for things like the grabber to be a part of an outer `gui` or `window` element.  I might not bother changing that in the foreseeable future though, as long as my current `hideGrabber` hack holds out ok.

Actually I haven't checked if `dat.gui` itself supports nested folders, but it does at least support lots of sibling folders in a gui.

**Comment by xinaesthete** [comment]
I'd thought I had this more or less correct, then remembered I'd left some bad magic numbers in the layout code. Not quite sure what's still wrong with the version on my machine right now, but once I've got it to the point where I consider it usable I'll submit a pull request.

**Comment by xinaesthete** [comment]
I think it's about right now, must go but will try to get around to making PR soon.

**Comment by mflux** [comment]
Done via https://github.com/dataarts/dat.guiVR/pull/80
