### ISSUE TITLE
non-visible GUIs still capture input

### ISSUE THREAD

**Issue by customlogic** [dataarts/dat.guiVR#67]

**Comment by xinaesthete** [comment]
I'm looking into this as it becomes extra problematic with collapsed folders.

I'm in the process of checking in a change that I believe is correct in fixing the bug, although at present it means extra work is done to generate a list of visible hitscan objects and I don't (yet) do any caching of that.  The extra expense may or may not be trivial, I suspect there could be some implications to garbage generated, which is not what anyone wants in a VR application.

Should be fairly easy to add the caching, but I'd rather do it in a way that avoided too much extra responsibility on the part of individual controllers.

**Comment by mflux** [comment]
I did notice this got fixed during testing. Great work!
