### ISSUE TITLE
Error when creating dropdown

### ISSUE THREAD

**Issue by dagudelos** [dataarts/dat.guiVR#84]
Hi dataarts, when i setup the dropdown, the following error comes: "labelInteraction.updateLabel is not a function" . In examples, the error occur too. This is my code:

gui.add(config, 'zoom',{ S: 100, M: 50, C: 0 } ); 

And the control, can't generate the dropdown. Thanks for your great work!

**Comment by mflux** [comment]
Will take a look thanks!
